apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: discovery-engine-role
rules:
- apiGroups: ["*"]
  resources: ["pods", "services", "deployments", "endpoints", "namespaces", "nodes","replicasets", "statefulsets", "daemonsets", "secrets"]
  verbs: ["get", "list", "watch","create", "update", "delete"]