apiVersion: v1
kind: Service
metadata:
  name: discovery-engine
  labels:
    service: discovery-engine
spec:
  ports:
  - port: 9089
    targetPort: 9089
    protocol: TCP
  selector:
    app: discovery-engine