application:
  name: knoxautopolicy
  network:
    operation-mode: 1                         # 1: cronjob | 2: one-time-job
    operation-trigger: 100
    cron-job-time-interval: "0h0m10s"         # format: XhYmZs 
    network-log-limit: 100000
    network-log-from: "hubble"                # db|hubble|kafka
    network-log-file: "./flow.json"           # file path
    network-policy-to: "db"              # db, file
    network-policy-dir: "./"
  system:
    operation-mode: 1                         # 1: cronjob | 2: one-time-job
    operation-trigger: 100
    cron-job-time-interval: "0h0m10s"         # format: XhYmZs
    system-log-from: "kafka"                     # db|kubearmor|kafka
    system-log-limit: 100000
    system-log-file: "./log.json"             # file path
    system-policy-to: "db"               # db, file
    system-policy-dir: "./"
  cluster:
    cluster-info-from: "k8sclient"            # k8sclient|accuknox
    #cluster-mgmt-url: "http://cluster-management-service.accuknox-dev-cluster-mgmt.svc.cluster.local/cm"
    cluster-mgmt-url: "http://localhost:8080"

database:
  driver: mysql
  host: 127.0.0.1
  port: 3306
  user: root
  password: password
  dbname: accuknox
  table-network-log: network_log
  table-network-policy: network_policy
  table-system-log: system_log
  table-system-alert: system_alert
  table-system-policy: system_policy

feed-consumer:
  kafka:
    number-of-consumers: 3
    broker-address-family: v4
    session-timeout-ms: 6000
    auto-offset-reset: "earliest"
    # auto-offset-reset: "latest"
    bootstrap-servers: "dev-kafka-kafka-external-bootstrap.accuknox-dev-kafka.svc.cluster.local:9095"
    group-id: knoxautopolicy
    topics: 
      - cilium-telemetry-new
      - cilium-telemetry
      - kubearmor-syslogs
    security:
      protocol: SSL
    ssl:
      enabled: true
    ca:
      location: /kafka-ssl/ca.pem
    keystore:
      location: /kafka-ssl/user.p12
      pword: DHmHwNYy22At
    events:
      buffer: 50

logging:
  level: "INFO"

# kubectl -n kube-system port-forward service/hubble-relay --address 0.0.0.0 --address :: 4245:80
cilium-hubble:
  url: localhost
  port: 4245

kubearmor:
  url: localhost
  port: 32767
