application:
  name: knoxautopolicy
  network:
    operation-mode: 1                         # 1: cronjob | 2: one-time-job
    operation-trigger: 100
    cron-job-time-interval: "0h0m10s"         # format: XhYmZs 
    network-log-limit: 100000
    network-log-from: "hubble"                # db|hubble|feed-consumer
    network-log-file: "./flow.json"           # file path
    network-policy-to: "db"              # db, file
    network-policy-dir: "./"
    namespace-filter:
      - "!kube-system"
  system:
    operation-mode: 1                         # 1: cronjob | 2: one-time-job
    operation-trigger: 100
    cron-job-time-interval: "0h0m10s"         # format: XhYmZs
    system-log-from: "kafka"                     # db|kubearmor|feed-consumer
    system-log-limit: 100000
    system-log-file: "./log.json"             # file path
    system-policy-to: "db"               # db, file
    system-policy-dir: "./"
  cluster:
    cluster-info-from: "k8sclient"            # k8sclient|accuknox
    #cluster-mgmt-url: "http://cluster-management-service.accuknox-dev-cluster-mgmt.svc.cluster.local/cm"
    cluster-mgmt-url: "http://localhost:8080"

observability: 
  enable: true
  cron-job-time-interval: "0h0m10s"         # format: XhYmZs
  dbname: ./accuknox-obs.db
  system-observability: true
  network-observability: false
  write-logs-to-db: false
  summary-jobs:
    publisher: true
    write-summary-to-db: false
    cron-interval: "0h1m00s"

database:
  driver: sqlite3
  host: 127.0.0.1
  port: 3306
  user: root
  password: password
  dbname: accuknox
  sqlite-db-path: ./accuknox.db
  table-network-log: network_log
  table-network-policy: network_policy
  table-system-log: system_log
  table-system-alert: system_alert
  table-system-policy: system_policy

feed-consumer:
  driver: "pulsar"
  servers:
    - "pulsar-proxy.accuknox-dev-pulsar.svc.cluster.local:6650"
  topic: 
    cilium: "persistent://accuknox/datapipeline/ciliumalertsrawflow"
    kubearmor: "persistent://accuknox/datapipeline/kubearmoralertsrawflow"
  encryption:
    enable: false
    ca-cert: /kafka-ssl/ca.pem 
  auth:
    enable: false
    cert: /kafka-ssl/user.cert.pem
    key: /kafka-ssl/user.key.pem

logging:
  level: "INFO"

# kubectl -n kube-system port-forward service/hubble-relay --address 0.0.0.0 --address :: 4245:80
cilium-hubble:
  url: localhost
  port: 4245

kubearmor:
  url: localhost
  port: 32767

# Recommended policies configuration
recommend:
  operation-mode: 1                       # 1: cronjob | 2: one-time-job
  cron-job-time-interval: "1h0m00s"       # format: XhYmZs
  recommend-host-policy: true
  template-version: "v0.2.1"

# license
license:
  enabled: false
  # validate can be user-id or platform-uuid
  validate: "user-id"

pprof: false