name: Push Policy Discovery Image to Docker

on:
  push:
    branches: [master,dev,AK-Dev,v*]

jobs:
  push-docker-img:
    name: Create discovery engine img
    if: github.repository == 'accuknox/discovery-engine'
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Generate artifacts
        run: ./src/build/build_knoxautopolicy.sh
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_AUTHTOK }}
      - name: Push images to Docker
        run: ./src/build/push_knoxautopolicy.sh
