on:
  push:
    # Sequence of patterns matched against refs/tags
    branches:
      - 'dev'
      - 'v*'

  create: 
    branches:
      - 'v*'

name: Create discovery engine release after testing the image

jobs:
  build:
    name: Create discovery engine Release
    if: github.repository == 'accuknox/discovery-engine'
    runs-on: ubuntu-18.04
    timeout-minutes: 20
    steps:
      - name: Checkout discovery engine code
        uses: actions/checkout@v2

      - name: Setup Enviroment
        id: vars
        run: |
          if [ ${{ github.ref }} == "refs/heads/dev" ]; then
            echo ::set-output name=tag::latest
          else 
            echo ::set-output name=tag::${GITHUB_REF#refs/*/}
          fi
        
          # setup kubernetes environment
          ./k3s/install_k3s.sh


      - name: Generate discovery engine artifacts
        run: |
            GITHUB_SHA=$GITHUB_SHA ./src/build/build_knoxautopolicy.sh ${{ steps.vars.outputs.tag }}

      - name: Run discovery engine
        run: |
            kubectl apply -f deployments/k8s/ && kubectl wait --for=condition=ready --timeout=5m -n default pod -l container=knoxautopolicy
            kubectl get pods -A

#TODO: add the following tests after they are fixed
      # - name: Test discovery engine
      #   run: |
      #       ./tests/test-scenarios-local.sh ${{ steps.vars.outputs.tag }}

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_AUTHTOK }}

      - name: Push discovery engine images to Docker
        run: |
            ./src/build/push_knoxautopolicy.sh ${{ steps.vars.outputs.tag }}
