on:
  push:
    # Sequence of patterns matched against refs/tags
    branches:
      - 'v*'

name: discovery engine stable release update

jobs:
  build:
    name: Create discovery engine Release - 18.04
    if: github.repository == 'accuknox/discovery-engine'
    runs-on: ubuntu-18.04
    timeout-minutes: 20
    steps:
      - name: Checkout discovery engine code
        uses: actions/checkout@v2
        with:
          ref: dev

      - name: Pull Docker Hub image
        id: match
        run: |
            value=`cat STABLE-RELEASE`
            if [ ${{ github.ref }} == refs/heads/$value ]; then
            docker pull docker.io/accuknox/knoxautopolicy:$value
            docker image accuknox/knoxautopolicy:$value accuknox/knoxautopolicy:stable
              echo ::set-output name=tag::true
            else
              echo ::set-output name=tag::false
            fi

      - name: Login to Docker Hub
        if: steps.match.outputs.tag == 'true'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_AUTHTOK }}

      - name: Push discovery engine images to Docker
        if: steps.match.outputs.tag == 'true'
        run:  ./src/build/push_knoxautopolicy.sh stable

