on:
  push:
    # Sequence of patterns matched against refs/tags
    branches:
      - 'dev'

    paths:
      - 'STABLE-RELEASE'

name: discovery engine stable release

jobs:
  build:
    name: Create discovery engine stable release
    if: github.repository == 'kubearmor/discovery-engine'
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    steps:
      - name: Checkout discovery engine code
        uses: actions/checkout@v2

      - name: Pull Docker Hub image
        run: |
            value=`cat STABLE-RELEASE`
            docker pull docker.io/kubearmor/knoxautopolicy:$value
            docker image tag kubearmor/knoxautopolicy:$value kubearmor/knoxautopolicy:stable

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_AUTHTOK }}

      - name: Push discovery engine images to Docker
        run:  ./src/build/push_knoxautopolicy.sh stable
